hello.lo: /Users/gsoares/workspace/php-extension/php-7.1.9/ext/hello/hello.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/gsoares/workspace/php-extension/php-7.1.9/ext/hello $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/gsoares/workspace/php-extension/php-7.1.9/ext/hello/hello.c -o hello.lo 
$(phplibdir)/hello.la: ./hello.la
	$(LIBTOOL) --mode=install cp ./hello.la $(phplibdir)

./hello.la: $(shared_objects_hello) $(HELLO_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_hello) $(HELLO_SHARED_LIBADD)

